# -*- coding: utf-8 -*-
"""Class Comp Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAUUq3LZX0DNmLWTJKDJRNawBknav81E
"""

# ==========================================
# CELL 1: CONNECT TO GOOGLE SHEETS DIRECTLY
# ==========================================
from google.colab import auth
import gspread
from google.auth import default
import pandas as pd

# 1. Authenticate
print("🔐 Authenticating...")
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
print("✅ Connected to Google Sheets!")

# 2. Helper Function: Load Sheet by Name
def load_sheet_by_name(filename):
    try:
        # Opens the spreadsheet and grabs the first tab (sheet1)
        wb = gc.open(filename)
        rows = wb.sheet1.get_all_records()
        df = pd.DataFrame(rows)
        print(f"✅ Loaded: {filename} ({len(df)} rows)")
        return df
    except Exception as e:
        print(f"❌ Error loading '{filename}': {e}")
        return None

def load_sheet_by_key(sheet_key):
    try:
        # Opens by ID instead of Name
        wb = gc.open_by_key(sheet_key)
        rows = wb.sheet1.get_all_records()
        df = pd.DataFrame(rows)
        print(f"✅ Loaded Sheet (ID: {sheet_key[:5]}...) - {len(df)} rows")
        return df
    except Exception as e:
        print(f"❌ Error loading Key '{sheet_key}': {e}")
        return None

# ==========================================
# CELL 2: LOAD SPECIFIC DATA
# ==========================================
# Update these names EXACTLY as they appear in Google Drive

# 1. The Boundary File (TANC Locals)
df_locals = load_sheet_by_name("Alameda County - Census Tracts x TANC locals")

# 2. The Rent Data (RAP)
df_rap = load_sheet_by_name("Rent Registry as of 05.29.2024")

# 3. The Census Data (The "Messy" Sheet)
df_census = load_sheet_by_name("Oakland Demographic Data Messy (Updated 11-24)")

# Preview to check
if df_locals is not None:
    print("\n👀 Preview of Locals Data:")
    print(df_locals.head(3))

# ==========================================
# CELL 3: STANDARDIZE THE IDs
# ==========================================

def clean_tract_id(value):
    """
    Converts messy inputs (4001, "Census Tract 4001", 4028.01)
    into a clean 6-digit string (400100, 402801).
    """
    if pd.isna(value) or value == '':
        return None

    # Force to string
    s = str(value)

    # 1. Remove text like "Census Tract", "Alameda", etc.
    # Keeps only numbers and dots.
    import re
    nums = re.findall(r"(\d+\.?\d*)", s)

    if not nums:
        return None

    # Take the first number found (e.g. "4001" from "Census Tract 4001")
    raw_num = float(nums[0])

    # 2. Handle the decimal/scale logic
    # If it looks like a short tract (e.g. 4001), multiply by 100
    # If it looks like a full FIPS (e.g. 400100), keep it.
    # Heuristic: Tracts in Oakland are usually < 10,000.
    if raw_num < 10000:
        clean_num = int(raw_num * 100)
    else:
        clean_num = int(raw_num)

    # 3. Return as 6-digit string for easy matching
    return str(clean_num).zfill(6)


print("🧹 Cleaning IDs...")

# Clean TANC Locals Sheet
# Based on screenshot, column is "Census Tract" or "Label (Grouping)"
if 'Census Tract' in df_locals.columns:
    df_locals['Match_ID'] = df_locals['Census Tract'].apply(clean_tract_id)
elif 'Label (Grouping)' in df_locals.columns:
    df_locals['Match_ID'] = df_locals['Label (Grouping)'].apply(clean_tract_id)

# Clean Census Sheet
# Based on screenshot, column might be "GEO_ID" or "Label (Grouping)"
# Note: If GEO_ID is "1400000US06001400100", the regex will grab 1400000...
# We might need specific logic if you use the GEO_ID column.
# Let's assume you use the "Label (Grouping)" column which is easier.
if df_census is not None and 'Label (Grouping)' in df_census.columns:
    df_census['Match_ID'] = df_census['Label (Grouping)'].apply(clean_tract_id)

# Clean RAP (Rent) Sheet
# This requires geocoding first (as discussed), but if you have a tract column:
if df_rap is not None and 'Census Tract' in df_rap.columns:
    df_rap['Match_ID'] = df_rap['Census Tract'].apply(clean_tract_id)

print("✅ IDs Standardized. Ready to Merge on 'Match_ID'.")
print(df_locals[['Match_ID', 'TANC Local']].head())

!pip install cenpy geopandas mapclassify folium matplotlib

# ==========================================
# CELL 4: MERGE & VISUALIZE (FIXED)
# ==========================================
import geopandas as gpd
import pandas as pd

# 1. FETCH THE SHAPES DIRECTLY
print("🗺️ Downloading 2023 California Tracts...")
shapefile_url = "https://www2.census.gov/geo/tiger/TIGER2023/TRACT/tl_2023_06_tract.zip"
shapes_gdf = gpd.read_file(shapefile_url)

# 2. FILTER FOR ALAMEDA COUNTY ('001')
print("✂️ Filtering for Alameda County...")
shapes_gdf = shapes_gdf[shapes_gdf['COUNTYFP'] == '001'].copy()

# 3. CLEAN THE IDs
# Extract last 6 digits to match clean data
shapes_gdf['Match_ID'] = shapes_gdf['GEOID'].str[-6:]

# 4. MERGE DATA
if 'df_locals' in locals():
    merged_map = shapes_gdf.merge(df_locals[['Match_ID', 'TANC Local']], on='Match_ID', how='inner')
    print(f"✅ Merged! Found {len(merged_map)} tracts with TANC definitions.")
else:
    print("❌ Error: 'df_locals' missing. Run Step 2 (Load Data) first.")

# 5. CREATE THE INTERACTIVE MAP
if 'merged_map' in locals() and not merged_map.empty:
    # We add .reset_index() so 'TANC Local' stays a column we can use for coloring.
    final_map = merged_map.dissolve(by='TANC Local', aggfunc='first').reset_index()

    print("🎨 Rendering Map...")
    m = final_map.explore(
        column='TANC Local',
        cmap='Set1',             # Color scheme
        tooltip=['TANC Local'],  # Hover info
        tiles='CartoDB positron',
        style_kwds={'fillOpacity': 0.6, 'weight': 2}
    )
    display(m)
else:
    print("⚠️ No data to map.")

# ==========================================
# CELL 5: FINAL MERGE & FACT SHEETS
# ==========================================
import pandas as pd

# 1. DEFINE IDs
LOCALS_ID = '1U5ke21ILdvKKX_PBGiqeZKfBtT8lN6fgU6SrFBZhbV0'
DEMO_ID   = '1RUs9nfVatsvfFokfN5orB2qMBb8cFaGMcu8VZrrqUq0'

print("QC: Loading Sheets...")
df_locals = load_sheet_by_key(LOCALS_ID)
df_demo   = load_sheet_by_key(DEMO_ID)

if df_locals is not None and df_demo is not None:
    # 2. STANDARDIZE THE IDs (Crucial Step)
    # We create a 'Match_ID' column in both sheets that is ALWAYS a string (e.g. "400100")

    # Clean Locals Sheet
    if 'Census Tract' in df_locals.columns:
        df_locals['Match_ID'] = df_locals['Census Tract'].apply(clean_tract_id).astype(str)

    # Clean Demo Sheet
    if 'Label (Grouping)' in df_demo.columns:
        df_demo['Match_ID'] = df_demo['Label (Grouping)'].apply(clean_tract_id).astype(str)

    # 3. CLEAN NUMERIC COLUMNS (In Demo Data)
    # Remove commas from "1,200" and ensure they are numbers
    cols_to_fix = ['Total', 'White', 'Black', 'Asian', 'Hispanic']
    for col in df_demo.columns:
        if col in cols_to_fix:
             # Force to string, remove commas, convert to number
            df_demo[col] = pd.to_numeric(
                df_demo[col].astype(str).str.replace(',', '', regex=True),
                errors='coerce'
            ).fillna(0)

    # 4. MERGE DATA
    # First, merge Locals into the Map Shapes (from Cell 4)
    # Ensure 'shapes_gdf' exists from the previous step!
    if 'shapes_gdf' in locals():
        print("QC: Merging Locals into Map...")
        # Ensure map IDs are strings too
        shapes_gdf['Match_ID'] = shapes_gdf['Match_ID'].astype(str)
        merged_map = shapes_gdf.merge(df_locals[['Match_ID', 'TANC Local']], on='Match_ID', how='inner')

        # Next, merge Demographic Data into that Map
        print(f"QC: Merging Demographics ({len(df_demo)} rows)...")
        full_data = merged_map.merge(df_demo, on='Match_ID', how='left')

        # 5. CALCULATE FACT SHEET
        if 'Total' in full_data.columns:
            fact_sheet = full_data.groupby('TANC Local').agg({
                'Total': 'sum',
                'White': 'sum',
                'Black': 'sum',
                'Asian': 'sum'
            }).reset_index()

            # Calculate Percentages
            fact_sheet['% Black'] = (fact_sheet['Black'] / fact_sheet['Total'] * 100).round(1)
            fact_sheet['% White'] = (fact_sheet['White'] / fact_sheet['Total'] * 100).round(1)

            print("\n📊 FINAL FACT SHEET TABLE:")
            display(fact_sheet)

            # 6. MAKE THE HEAT MAP
            # We map the % Black population per Local
            local_stats_map = full_data.dissolve(by='TANC Local', aggfunc='sum').reset_index()
            local_stats_map['Pct_Black'] = (local_stats_map['Black'] / local_stats_map['Total'] * 100).round(1)

            print("🎨 Rendering Data Map (Percent Black)...")
            m = local_stats_map.explore(
                column='Pct_Black',
                cmap='OrRd', # Red color scheme
                tooltip=['TANC Local', 'Total', 'Pct_Black'],
                tiles='CartoDB positron',
                style_kwds={'fillOpacity': 0.7}
            )
            display(m)
        else:
            print("❌ Error: 'Total' column missing. Check column names in df_demo.")
    else:
        print("❌ Error: 'shapes_gdf' missing. Please re-run Cell 4 to download the map shapes.")
else:
    print("❌ Error: Could not load one of the sheets.")

# @title 🗺️ TANC Demographic Map
# @markdown **Instructions:** Select a metric from the dropdown on the right, then run the cell (Ctrl+Enter).

import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

# 1. SETUP THE DROPDOWN (This creates the native UI)
metric = "% Asian" # @param ["% Black", "% White", "% Asian", "% Hispanic"]

# 2. CHECK DATA
if 'dashboard_data' not in locals():
    print("⚠️ Data missing. Please run the 'Data Loading' cells first.")
else:
    # 3. RENDER MAP
    print(f"🎨 Rendering map for {metric}...")

    # Color scheme
    cmaps = {'% Black': 'Reds', '% White': 'Blues', '% Asian': 'Greens', '% Hispanic': 'Oranges'}

    # Oak coord
    oak_lat, oak_lon = 37.8044, -122.2712

    m = dashboard_data.explore(
        column=metric,
        cmap=cmaps.get(metric, 'Purples'),
        tooltip=['TANC Local', 'Total', metric],
        tiles='CartoDB positron',
        location=[oak_lat, oak_lon],
        zoom_start=12,
        style_kwds={'fillOpacity': 0.7, 'weight': 1},
        legend_kwds={'caption': f'{metric} by Local'}
    )
    display(m)

import ipywidgets as widgets
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, clear_output

# ==========================================
# 1. DATA PREP & SAFETY CHECK
# ==========================================
# We check if 'full_data' exists (created in your Merge step).
# If not, we warn you instead of crashing.
if 'full_data' not in locals():
    print("🛑 ERROR: 'full_data' is missing.")
    print("👉 Please scroll up and run the cell that merges your data (usually Cell 5) first.")
else:
    # Create a clean working copy for the dashboard
    # We group by 'TANC Local' to get the aggregate numbers
    dash_df = full_data.dissolve(by='TANC Local', aggfunc='sum').reset_index()
    dash_df = dash_df.fillna(0)

    # Avoid divide-by-zero errors by ensuring Total is at least 1
    dash_df['Total_Safe'] = dash_df['Total'].replace(0, 1)

    # 2. Dynamic Column Detection
    # We map Display Name -> (Column Name, Color Map for Map, Hex Color for Graph)
    metrics_config = {
        '% Black': ('Black', 'Reds', '#d32f2f'),   # Red
        '% White': ('White', 'Blues', '#1976d2'),   # Blue
        '% Asian': ('Asian', 'Greens', '#388e3c')   # Green
    }

    # Check if Hispanic/Latino data exists in your sheet
    for candidate in ['Hispanic', 'Latino']:
        if candidate in dash_df.columns:
            metrics_config[f'% {candidate}'] = (candidate, 'Oranges', '#f57c00') # Orange
            break

    # 3. Calculate Percentages (Recalculated fresh to avoid stale data)
    for label, (raw_col, _, _) in metrics_config.items():
        dash_df[label] = (dash_df[raw_col] / dash_df['Total_Safe'] * 100).round(1)

    # ==========================================
    # 2. UI COMPONENTS (The Dropdowns)
    # ==========================================

    # A. MAP CONTROLS
    map_selector = widgets.Dropdown(
        options=list(metrics_config.keys()),
        value='% Black',
        description='Map Layer:',
        layout=widgets.Layout(width='300px')
    )

    # B. INSPECTOR CONTROLS (The Fix!)
    # This automatically pulls every unique Local name from your data.
    local_selector = widgets.Dropdown(
        options=sorted(dash_df['TANC Local'].unique()),
        description='Select Local:',
        layout=widgets.Layout(width='300px')
    )

    # Outputs
    out_map = widgets.Output()
    out_inspector = widgets.Output()

    # ==========================================
    # 3. RENDER FUNCTIONS
    # ==========================================

    def render_map(change):
        metric_label = change['new'] if isinstance(change, dict) else change
        raw_col, cmap_name, _ = metrics_config[metric_label]

        with out_map:
            clear_output(wait=True)
            # Create the interactive map
            m = dash_df.explore(
                column=metric_label,
                cmap=cmap_name,
                tiles='CartoDB positron',
                tooltip=['TANC Local', 'Total', metric_label],
                style_kwds={'fillOpacity': 0.7, 'weight': 1},
                legend_kwds={'caption': f'{metric_label} by Local'}
            )
            display(m)

    def render_inspector(change):
        local_name = change['new'] if isinstance(change, dict) else change
        # Grab the specific row for this Local
        row = dash_df[dash_df['TANC Local'] == local_name].iloc[0]

        with out_inspector:
            clear_output(wait=True)

            # 1. Print Fact Sheet
            print(f"🏢 FACT SHEET: {local_name.upper()}")
            print("=" * 45)
            print(f"👥 Total Population: {int(row['Total']):,}")
            print("-" * 45)

            # Prepare data for plot
            cats = []
            vals = []
            colors = []

            for label, (raw_col, _, hex_color) in metrics_config.items():
                count = int(row[raw_col])
                pct = row[label]
                # Nice formatted text output
                print(f" • {raw_col:<10} {count:>6,}  ({pct}%)")

                cats.append(raw_col)
                vals.append(count)
                colors.append(hex_color)

            print("=" * 45)

            # 2. Plot Bar Chart
            fig, ax = plt.subplots(figsize=(8, 4))
            sns.barplot(x=cats, y=vals, palette=colors, ax=ax)

            # Add numbers on top of bars
            for i, v in enumerate(vals):
                ax.text(i, v + (max(vals)*0.02), f"{v:,}", ha='center', fontweight='bold')

            ax.set_title(f"Demographics: {local_name}")
            ax.set_ylabel("Residents")
            sns.despine()
            plt.show()

    # ==========================================
    # 4. INITIALIZE & DISPLAY
    # ==========================================

    # Hook up event listeners (Make it interactive)
    map_selector.observe(render_map, names='value')
    local_selector.observe(render_inspector, names='value')

    # Trigger first render so it's not empty
    render_map(map_selector.value)
    render_inspector(local_selector.options[0])

    # Layout: Use Tabs to keep it clean
    tab_map = widgets.VBox([
        widgets.HTML("<h4>📍 Geographic Overview</h4><p>Select a demographic to visualize density.</p>"),
        map_selector,
        out_map
    ])

    tab_inspector = widgets.VBox([
        widgets.HTML("<h4>🔍 Local Deep Dive</h4><p>Select a specific TANC Local to see the raw numbers.</p>"),
        local_selector,
        out_inspector
    ])

    dashboard = widgets.Tab(children=[tab_map, tab_inspector])
    dashboard.set_title(0, "Map View")
    dashboard.set_title(1, "Local Inspector")

    display(widgets.HTML("<h3>🏘️ TANC Class Composition Dashboard</h3>"))
    display(dashboard)

import ipywidgets as widgets
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, clear_output

# ==========================================
# 1. PREPARE THE DATA (Safety Check)
# ==========================================
# Ensure we have the safe plotting data from previous steps
if 'full_data' in locals():
    # Group by Local to get the "Fact Sheet" data ready
    dashboard_data = full_data.dissolve(by='TANC Local', aggfunc='sum').reset_index()
    dashboard_data = dashboard_data.fillna(0)

    # Recalculate percentages to be safe
    dashboard_data['Total_Safe'] = dashboard_data['Total'].replace(0, 1)
    dashboard_data['% Black'] = (dashboard_data['Black'] / dashboard_data['Total_Safe'] * 100).round(1)
    dashboard_data['% White'] = (dashboard_data['White'] / dashboard_data['Total_Safe'] * 100).round(1)
    dashboard_data['% Asian'] = (dashboard_data['Asian'] / dashboard_data['Total_Safe'] * 100).round(1)

    # Check for Hispanic/Latino
    hisp_col = 'Hispanic' if 'Hispanic' in dashboard_data.columns else ('Latino' if 'Latino' in dashboard_data.columns else None)
    if hisp_col:
        dashboard_data['% Hispanic'] = (dashboard_data[hisp_col] / dashboard_data['Total_Safe'] * 100).round(1)

else:
    print("⚠️ Data missing. Please run the previous cells (Cell 5) first.")

# ==========================================
# 2. TAB 1: THE INTERACTIVE MAP
# ==========================================
map_dropdown = widgets.Dropdown(
    options=['% Black', '% White', '% Asian'] + (['% Hispanic'] if hisp_col else []),
    value='% Black',
    description='Metric:',
    layout=widgets.Layout(width='300px')
)

map_output = widgets.Output()

def render_map(change):
    col_name = change['new'] if isinstance(change, dict) else change
    with map_output:
        clear_output(wait=True)

        # Define color schemes
        cmaps = {'% Black': 'Reds', '% White': 'Blues', '% Asian': 'Greens', '% Hispanic': 'Oranges'}

        # Get the centroid of Oakland for stable zooming
        oak_lat, oak_lon = 37.8044, -122.2712

        # Render
        m = dashboard_data.explore(
            column=col_name,
            cmap=cmaps.get(col_name, 'Purples'),
            tooltip=['TANC Local', 'Total', col_name],
            tiles='CartoDB positron',
            location=[oak_lat, oak_lon],
            zoom_start=11, # Keeps the zoom stable-ish
            style_kwds={'fillOpacity': 0.7, 'weight': 1},
            legend_kwds={'caption': f'{col_name} by Local'}
        )
        display(m)

map_dropdown.observe(render_map, names='value')

# Trigger initial map load
with map_output:
    render_map(map_dropdown.value)

map_tab = widgets.VBox([
    widgets.HTML("<h3>📍 Geographic View</h3><p>Select a demographic to see density across the East Bay.</p>"),
    map_dropdown,
    map_output
])

# ==========================================
# 3. TAB 2: THE LOCAL INSPECTOR (Drill Down)
# ==========================================
# This allows you to select a specific Local and see the exact counts

inspector_dropdown = widgets.Dropdown(
    options=sorted(dashboard_data['TANC Local'].unique()),
    description='Select Local:',
    layout=widgets.Layout(width='400px')
)

inspector_output = widgets.Output()

def render_inspector(change):
    local_name = change['new'] if isinstance(change, dict) else change
    row = dashboard_data[dashboard_data['TANC Local'] == local_name].iloc[0]

    with inspector_output:
        clear_output(wait=True)

        # 1. Display The Raw Numbers Table
        print(f"\n📊 DEMOGRAPHIC SUMMARY: {local_name.upper()}")
        print("-" * 40)
        print(f"Total Population: {int(row['Total']):,}")
        print(f"Black Population: {int(row['Black']):,} ({row['% Black']}%)")
        print(f"White Population: {int(row['White']):,} ({row['% White']}%)")
        print(f"Asian Population: {int(row['Asian']):,} ({row['% Asian']}%)")
        if hisp_col:
            print(f"Hisp/Lat Population: {int(row[hisp_col]):,} ({row['% Hispanic']}%)")
        print("-" * 40 + "\n")

        # 2. Display a Quick Bar Chart
        fig, ax = plt.subplots(figsize=(8, 4))

        categories = ['Black', 'White', 'Asian']
        if hisp_col: categories.append(hisp_col)

        values = [row[cat] for cat in categories]
        colors = ['#d32f2f', '#1976d2', '#388e3c', '#f57c00'] # Red, Blue, Green, Orange

        sns.barplot(x=categories, y=values, palette=colors, ax=ax)
        ax.set_title(f"Demographics of {local_name}")
        ax.set_ylabel("Population Count")
        sns.despine()

        plt.show()

inspector_dropdown.observe(render_inspector, names='value')

# Trigger initial inspector load
with inspector_output:
    render_inspector(inspector_dropdown.options[0])

inspector_tab = widgets.VBox([
    widgets.HTML("<h3>🔍 Local Inspector</h3><p>Select a TANC Local to see specific population counts.</p>"),
    inspector_dropdown,
    inspector_output
])

# ==========================================
# 4. FINAL DASHBOARD DISPLAY
# ==========================================
dashboard = widgets.Tab(children=[map_tab, inspector_tab])
dashboard.set_title(0, 'Map View')
dashboard.set_title(1, 'Local Inspector')

display(dashboard)

# ==========================================
# DIAGNOSTICS: LIST ALL AVAILABLE SHEETS
# ==========================================
# This helps us see if permissions are the issue.
files = gc.list_spreadsheet_files()

print(f"I found {len(files)} spreadsheets available to this script.")
print("Here are the first 10:")
for f in files[:10]:
    print(f" - {f['name']} (ID: {f['id']})")

print("\nSearching for 'Oakland Demographic'...")
found = False
for f in files:
    if "Alameda County - Census Tracts x TANC locals" in f['name']:
        print(f"✅ FOUND IT! Name: {f['name']} | ID: {f['id']}")
        found = True
if not found:
    print("❌ NOT FOUND. Please check your permissions.")