import pandas as pd
import geopandas as gpd
import os
import config


def pct_change_with_cpi(old, new, cpi_factor=1.0):
    """Percent change after adjusting old value to new dollars via CPI factor."""
    if old is None or new is None or pd.isna(old) or pd.isna(new) or old == 0:
        return None
    adjusted_old = old * cpi_factor
    if adjusted_old == 0:
        return None
    return round((new - adjusted_old) / adjusted_old * 100, 1)


def crosswalk_weighted_avg(df_old: pd.DataFrame, crosswalk: pd.DataFrame, value_cols: list) -> pd.DataFrame:
    """
    Apply 2010-to-2020 tract crosswalk: weight each old-tract value by area_pct
    of the (old -> new) mapping. Returns one row per 2020 tract with weighted values.

    For tracts that didn't change, area_pct=1.0 -> values pass through.
    For 1->many splits, the old tract's values are distributed by area weight.
    For many->1 merges, the new tract aggregates weighted contributions.
    """
    # Join old data to crosswalk on 2010 tract id
    merged = crosswalk.merge(df_old, left_on='tract_2010', right_on='id', how='left')

    # Multiply each value column by area_pct
    for col in value_cols:
        if col in merged.columns:
            merged[f'{col}_weighted'] = merged[col] * merged['area_pct']

    # Sum (weighted) by 2020 tract id
    agg_dict = {f'{col}_weighted': 'sum' for col in value_cols if f'{col}_weighted' in merged.columns}
    out = merged.groupby('tract_2020').agg(agg_dict).reset_index()
    out = out.rename(columns={'tract_2020': 'id', **{f'{col}_weighted': col for col in value_cols}})
    return out


# CONFIG
MANUAL_LOCALS_FILE = "tanc_data_clean.csv" # Your existing sheet with "TANC Local" assignments
CENSUS_DATA_FILE = "census_fresh_data.csv" # Generated by step 2
MAP_FILE = "tanc_map_data.geojson"         # Your base map shapefile
OUTPUT_FILE = "public/data.geojson"

def main():
    print("🔄 Starting Data Merge...")

    # 1. Load Files
    if not os.path.exists(CENSUS_DATA_FILE):
        print(f"❌ Error: {CENSUS_DATA_FILE} not found. Run fetch_census.py first.")
        return

    df_census = pd.read_csv(CENSUS_DATA_FILE, dtype={'id': str})
    df_locals = pd.read_csv(MANUAL_LOCALS_FILE, dtype={'Match_ID': str})
    gdf = gpd.read_file(MAP_FILE)

    # 2. Prepare Locals Data (We only need the ID and the Local Name)
    # Assuming 'Match_ID' in your CSV matches the 'id' we generated from Census
    # And 'TANC Local' is the column name for the local chapter
    df_locals_subset = df_locals[['Match_ID', 'TANC Local']].copy()
    df_locals_subset = df_locals_subset.rename(columns={'Match_ID': 'id', 'TANC Local': 'tanc_local'})
    
    # Clean IDs to ensure they match (6 digits)
    df_locals_subset['id'] = df_locals_subset['id'].apply(lambda x: str(x).split('.')[0].zfill(6))

    # 3. Merge Census + Locals
    # We use a "Left" merge on Census to keep all census data, attaching Locals where they exist
    df_merged = df_census.merge(df_locals_subset, on='id', how='left')
    
    # Fill NaN locals with "Unassigned" or empty string if you prefer
    df_merged['tanc_local'] = df_merged['tanc_local'].fillna('')

    print(f"   Matched {df_merged['tanc_local'].ne('').sum()} tracts to TANC Locals.")

    # 4. Merge with Geography
    # Ensure GeoJSON has a matching ID column. Often it's 'TRACTCE' or 'TRACT'.
    # We'll try to find the 6-digit tract ID in the geojson.
    
    # Helper to find the matching column in GeoJSON
    geo_id_col = None
    for col in gdf.columns:
        if str(gdf[col].iloc[0]).zfill(6) in df_merged['id'].values:
            geo_id_col = col
            break
    
    if not geo_id_col:
        # Fallback: Create a normalized ID column in GeoJSON to match
        # Assuming GEOID usually ends with the tract ID
        gdf['id_match'] = gdf['GEOID'].apply(lambda x: str(x)[-6:])
        geo_id_col = 'id_match'

    print(f"   Merging Map using column: {geo_id_col}")
    
    # Merge GeoDataFrame with Data
    final_gdf = gdf.merge(df_merged, left_on=geo_id_col, right_on='id', how='inner')

    # 5. Clean up & Save
    # Keep only useful columns to keep file size down
    keep_cols = [
        'id', 'tanc_local', 'total_pop', 'median_hh_income', 'median_gross_rent',
        'rent_burden', 'unemployment', 'poverty_rate', 'vacancy_rate', 'median_year_built',
        'pct_white', 'pct_black', 'pct_hispanic', 'pct_asian', 'geometry'
    ]
    
    # Filter columns that actually exist
    final_cols = [c for c in keep_cols if c in final_gdf.columns]
    final_gdf = final_gdf[final_cols]

    # Save
    if not os.path.exists('public'): os.makedirs('public')
    final_gdf.to_file(OUTPUT_FILE, driver='GeoJSON')
    print(f"✅ Success! Map saved to {OUTPUT_FILE} with {len(final_gdf)} tracts.")

if __name__ == "__main__":
    main()